version: 2.1

parameters:
  UPLOAD_RESULTS:
    type: boolean
    default: false

orbs:
  codecov: codecov/codecov@4.0.1

executors:
  shared-executor:
    machine:
      image: ubuntu-2404:2024.11.1 # Machine image updates: https://circleci.com/developer/machine/image/ubuntu-2404
      resource_class: large
      docker_layer_caching: true

workflows:
  version: 2
  workflows:
    jobs:
      - run-tests:
          context: REDCap Tests
      - html-reports:
          context: REDCap Tests
          requires:
            - run-tests
          filters: pipeline.parameters.UPLOAD_RESULTS == true and pipeline.git.branch != "run-only-specified-features"

commands:
  setup-redcap:
    parameters:
      dir:
        type: string
        default: "."
    steps:
      - add_ssh_keys
      - run:
          name: Set environment variables
          command: |
            REDCAP_BRANCH=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq '.REDCAP_BRANCH')
            REDCAP_VERSION=99.99.99
            # REDCAP_BRANCH will be null for manually triggered builds, and empty string for scheduled builds (likely a CircleCI bug causing inconsistent behavior).
            if [[ "$REDCAP_BRANCH" != "null" && "$REDCAP_BRANCH" != "" ]]; then
              : # Do nothing
            elif [[ ${CIRCLE_BRANCH} == "dev" ]]; then
              REDCAP_BRANCH=master
            else # Use the tag version specified in cypress.env.json.example
              REDCAP_VERSION=`cat cypress.env.json.example|grep redcap_version|cut -d'"' -f 4`
              REDCAP_BRANCH=$REDCAP_VERSION
            fi

            echo Setting REDCAP_BRANCH to $REDCAP_BRANCH
            echo "export REDCAP_BRANCH=$REDCAP_BRANCH" >> $BASH_ENV

            echo Setting REDCAP_VERSION to $REDCAP_VERSION
            echo "export REDCAP_VERSION=$REDCAP_VERSION" >> $BASH_ENV
            
            UPLOAD_RESULTS=<< pipeline.parameters.UPLOAD_RESULTS >>
            echo Setting UPLOAD_RESULTS to $UPLOAD_RESULTS
            echo "export UPLOAD_RESULTS=$UPLOAD_RESULTS" >> $BASH_ENV

            echo "export COMMIT_INFO_MESSAGE=\"redcap branch '$REDCAP_BRANCH', redcap_cypress branch '${CIRCLE_BRANCH}'\"" >> $BASH_ENV
            echo "export COMMIT_INFO_BRANCH='-'" >> $BASH_ENV
            echo "export COMMIT_INFO_EMAIL='-'" >> $BASH_ENV
            echo "export COMMIT_INFO_AUTHOR='-'" >> $BASH_ENV
      - run:
          name: Build the REDCap Image
          command: |
            cd << parameters.dir >>
            git clone --branch main https://github.com/vanderbilt-redcap/redcap_docker ../redcap_docker
            cd ../redcap_docker
            git log -1 # Include current commit in build logs
            awk '
                { print }
                /TEMPLATE_PHP_INI: production/ {
                    print "      PHP_EXTENSION_XDEBUG: 1"
                    print "      REDCAP_VERSION: ${REDCAP_VERSION:-} # currently only needed for xdebug in cloud builds"
                }
                /# - ..\/redcap_source\/:\/var\/www\/html/ {
                    print "      - ../redcap_source/:/var/www/html/:Z"
                    print "      - ../project/coverage-report/:/tmp/path/coverage-report:Z"
                    print "      - ../project/coverage/:/tmp/path/coverage:Z"
                }
            ' "docker-compose.yml" > "awk.tmp" && mv "awk.tmp" "docker-compose.yml"
      - run:
          name: Get REDCap Source
          command: |
            cd << parameters.dir >>/..
            mkdir redcap_source
            cd redcap_source
            git clone --depth=1 --branch=$REDCAP_BRANCH git@github.com:vanderbilt-redcap/REDCap.git redcap_v${REDCAP_VERSION}
            git -C redcap_v${REDCAP_VERSION} log -1 # Include current commit in build logs
            cp -a redcap_v${REDCAP_VERSION}/Resources/install_files/redcap/* .
            cp -a redcap_v${REDCAP_VERSION}/Resources/nonversioned_files/* .
            cp /home/circleci/project/.circleci/redcap_install_files/* .

            if [[ ${CIRCLE_BRANCH} == "dev" ]]; then
              echo Checking out the "testing" branch of the EM Framework...
              export EM_FRAMEWORK_PATH=external_modules
              GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_50cfaf7ca7707739903a172fa25559c3" git clone --depth=1 git@github.com:vanderbilt-redcap/external-module-framework.git $EM_FRAMEWORK_PATH
            else
              export EM_FRAMEWORK_PATH=redcap_v${REDCAP_VERSION}/ExternalModules
            fi

            echo Copy examples modules in so the Module Development Examples module tests run
            cp -a $EM_FRAMEWORK_PATH/docs/example_modules/* modules/

jobs:
  run-tests:
    executor: shared-executor
    parallelism: 1
    steps:
      - checkout
      - setup-redcap
      - run:
          name: Start Docker REDCap Container
          command: |
            cd /home/circleci/redcap_docker
            docker-compose up -d
      - run:
          name: Install composer dependencies
          command: |
            docker exec -it redcap_docker-app-1 sh -c "cd /var/www/html/redcap_v${REDCAP_VERSION} && COMPOSER_DISABLE_XDEBUG_WARN=1 composer require --dev phpunit/php-code-coverage:^11"
      - run:
          name: Permissions on coverage files
          command: |
            docker exec -it redcap_docker-app-1 sh -c "chmod 777 /tmp/path/coverage"
      - run:
          name: Change eDocs & Temp folder permissions
          command: |
            sudo chmod 777 /home/circleci/edocs
      - run:
          name: Configure Cypress environment
          command: |
            cd /home/circleci/project
            sed s/PID/$PROJECT_ID/g cypress.config.js.example > cypress.config.js
            mv cypress.env.json.example cypress.env.json
            # Favor the REDCAP_VERSION CircleCI parameter over the "redcap_version" value in cypress.env.json
            awk '{ gsub(/"redcap_version": ".*",/, "\"redcap_version\": \"'$REDCAP_VERSION'\","); print }' cypress.env.json > awk-temp && mv awk-temp cypress.env.json
      - restore_cache:
          keys:
            - npm-install-v3-{{ checksum "package-lock.json" }}
      - run:
          name: Install Cypress
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use stable
            if [ ! -d node_modules ]; then
              # Only run npm install of node_modules wasn't created via restore_cache above
              npm install
            fi
      - save_cache:
          paths:
            - ~/project/node_modules
            - ~/.cache/Cypress
          key: npm-install-v3-{{ checksum "package-lock.json" }}
      - run:
          name: npm run redcap_rsvc:install
          command: |
            npm run redcap_rsvc:install
      - run:
          name: Run Tests
          command: |
            export UID # Referenced in docker-compose.yml by 'if running via automation' RCTF steps
            CYPRESS_prettyEnabled=true npx cypress run --record --key $RECORD_KEY --parallel --group core-tests --browser chrome --reporter junit --reporter-options=mochaFile=coverage/test-results/[hash].xml || true
      - run:
          name: Coverage Report
          command: |
            docker exec -i redcap_docker-app-1 php /var/www/html/phpcov.phar merge --clover /tmp/path/coverage-report/merged-coverage-${CIRCLE_NODE_INDEX}.xml /tmp/path/coverage
      - run:
          name: Debug Workspace Contents
          command: ls -l /home/circleci/project/coverage-report
      - run:
          name: Debug Cypress Videos
          command: ls -l /home/circleci/project/cypress/videos
      - persist_to_workspace:
          root: .
          paths:
            - coverage-report
            - coverage
            - cypress/videos
            - redcap_rsvc

  html-reports:
    executor: shared-executor
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project/coverage
      - setup-redcap:
          dir: "/home/circleci/project/"
      - run:
          name: Start Docker REDCap Container
          command: |
            cd /home/circleci/redcap_docker
            docker-compose up -d
      - run:
          name: Coverage Report
          command: |
            docker exec -i redcap_docker-app-1 php /var/www/html/phpcov.phar merge --html /tmp/path/coverage-report/html-report /tmp/path/coverage
      - run:
          name: Push to Repository
          command: |
            cd /home/circleci/project
            GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_dba1897a8caca68e1a8a5c2185311de3" git clone --depth=1 git@github.com:vanderbilt-redcap/redcap_cypress_build_reports.git
            cd coverage-report/html-report
            # Run the zip command from inside the dir of files we want to include to avoid extraneous parent dirs in the zip
            sudo zip -r ../../redcap_cypress_build_reports/"html-report-${REDCAP_VERSION}.zip" *
            cd ../../redcap_cypress_build_reports
            git add "html-report-${REDCAP_VERSION}.zip"
            git commit -m "Add latest HTML Report for version ${REDCAP_VERSION}"
            GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_dba1897a8caca68e1a8a5c2185311de3" git push

      - store_artifacts:
          path: /home/circleci/project/coverage/cypress/videos
          destination: /home/circleci/project/coverage/cypress/videos

      - persist_to_workspace:
          root: .
          paths:
            - coverage-report
